/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ApartmentOutlined: typeof import('@ant-design/icons-vue')['ApartmentOutlined']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    GithubOutlined: typeof import('@ant-design/icons-vue')['GithubOutlined']
    GlobalSettings: typeof import('./src/components/layout/GlobalSettings.vue')['default']
    HolidayTheme: typeof import('./src/components/base/HolidayTheme.vue')['default']
    LocaleSelect: typeof import('./src/components/base/LocaleSelect.vue')['default']
    LockOutlined: typeof import('@ant-design/icons-vue')['LockOutlined']
    MemorialTheme: typeof import('./src/components/base/MemorialTheme.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderCaptcha: typeof import('./src/components/base/SliderCaptcha.vue')['default']
    ThemeSwitch: typeof import('./src/components/base/ThemeSwitch.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
