name: Generate Changelog

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'CHANGELOG.md'
      - '.github/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          configurationFile: .github/changelog-config.json
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "📝 docs(changelog): Update CHANGELOG.md" || exit 0
          git push 